### PR TITLE
Defi motoko example

### PR DESCRIPTION
**Pull request by tarek-eg**
I will start working on this in the meantime.
It's a bigger example and hopefully we get more learning from it.
@lastmjs would that be ok?

closes https://github.com/demergent-labs/azle/issues/277

### CODE REVIEW

**Comment by lastmjs** [comment]
Yes, if you could comment in the issue or create it and link to the example so we all know what you're working on

**Comment by lastmjs** [comment]
We should also check with @dansteren. You haven't started on this one have you?

**Comment by dansteren** [comment]
Sorry, still getting back into the swing of github's notifications. No, I haven't started this one. You're good to go @tarek-eg.

**Comment by tarek-eg** [comment]
The typescript code is in `src/defi` and canister name is `defi`
I have kept the motoko version in `src/defi_dapp` to help while I am porting the files to typescript and I was planning to remove it after I complete all.

The only remaining work is porting main.mo to main.ts and the tests.

**Pull request merged**
